# Generated by Django 3.2.6 on 2021-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=100, primary_key=True, serialize=False)),
                ('link', models.CharField(db_column='Link', max_length=100)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_column='Score')),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('change', models.IntegerField(db_column='Change')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp')),
            ],
            options={
                'db_table': 'scores_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
