# Generated by Django 3.2.6 on 2021-08-25 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='Timestamp', default=django.utils.timezone.now)),
                ('added_by', models.CharField(db_column='AddedBy', max_length=45)),
                ('deleted_by', models.CharField(db_column='DeletedBy', max_length=45, null=True)),
                ('quote', models.TextField(db_column='Quote')),
                ('active', models.BooleanField(db_column='Active', default=True)),
                ('score_up', models.IntegerField(db_column='ScoreUp', default=0)),
                ('score_down', models.IntegerField(db_column='ScoreDown', default=0)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
